### ISSUE TITLE
bug: Cannot call rmtree on a symbolic link

### ISSUE THREAD

**Issue by trhyder** [polygoniq/engon#2]
# Bug Report

**engon version: 1.2.1**

**Current behavior:**

following the installation instructions on github produces the following console error:

`Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\shutil.py", line 756, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\shutil.py", line 754, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link`

**Expected behavior:**

The extension should install without a console error

**Steps to reproduce:**

Follow the Readme.md instruction on https://github.com/polygoniq/extensions/

**Comment by Griperis** [comment]
Hi @trhyder, your issue is related with symbolic links. Don't you use a addon folder that's actually a symbolic link?

**Comment by trhyder** [comment]
Thanks for looking at the issue. I am sorry but I don't know what symbolic links are. What instructions do I need to follow to install?

**Comment by Griperis** [comment]
Weird, then something creates symbolic links for you (symlink ~ shortcut to an other directory) or there are some unwanted files in the repo directory. Please can you try again with updated Blender (there were issues with removing extensions in Beta) and if the problem persists, I will need more information to help you. Could you please:
1. send a screenshot of how the repository is setup (Blender preferences)
2. check the content of the `Custom Directory` for the repository that's automatically created when the repository is added (send a screenshot what's inside)

Thank you very much!

**Comment by Griperis** [comment]
This issue is inactive for over a year without additional information, feel free to reopen, if the issue occurs again, we weren't able to replicate this.
